[package]
name = "rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# arrow = { version = "51.0.0", features = ["parquet"] }
# datafusion = "36.0.0"
evtx = "0.8.1"
parquet = "51.0.0"
